---
- name: Provision ec2 instances based on the environment
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    aws_host_name: testhost
    instance_types:
      Small: t2.micro
      Medium: t2.small
      Large: t2.medium
      Extra Large: t2.large
    inst_type: "{{ instance_types[host_size] }}"
    images:
      Windows2016: ami-00000000
      Windows2012: ami-00000000
      Linux: ami-942dd1f6
    image_type: "{{ images[host_os] }}"
    environments:
      Production: subnet-7795e13e
      Non-Production: subnet-009aa7986b32c5b47
      Shared Services: subnet-ee8ef589
      DMZ: subnet-0316165c451c9a8d8
    aws_subnet: "{{ environments[dep_env] }}"

  tasks:
  - name: Launch instances
    ec2:
        key_name: np_kp_aws
        region: ap-southeast-2
        instance_type: "{{ inst_type }}"
        image: ami-942dd1f6
        wait: yes
        group: default
        count: 1
        vpc_subnet_id: "{{ aws_subnet }}"
        assign_public_ip: no
        termination_protection: yes
        instance_tags:
          Name: "{{ hostname }}"
          AppGroup: "{{ app_group }}"
          Environment: "{{ dep_env }}"
          DataClass: "{{ data_class }}"
          OpWindow: "{{ op_window }}"
    register: ec2
