---
- name: Terminate instances
  hosts: localhost
  connection: local
  tasks:
    - name: turn off termination protection
      ec2:
        termination_protection: 'no'
        instance_tags:
          Name: "{{ host_name }}"
        
    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        instance_tags:
          Name: "{{ host_name }}"
